### ISSUE TITLE
How can I use it in Angular 6?

### ISSUE THREAD

**Issue by n1705771** [intel/generic-sensor-demos#55]
I would like to know how can I add accelerometer in angular project. I am using angular version 6.

Regards

**Comment by Honry** [comment]
@n1705771,  Generic Sensor is enabled by default in Chrome starting from Chrome 67(currently only Chrome implements it), you can build your Angular app with Chrome extension to use Accelerometer API.

**Comment by n1705771** [comment]
@Honry Thanks.

From the Accelerometer link above, I have selected below code and insert into my code. But I get the error " Cannot find name 'Accelerometer' ". Do I need install some npm module or add some script before using it? 
Sorry about the basic question, I am a beginner of API development...

```
let sensor = new Accelerometer();
sensor.start();

sensor.onreading = () => {
    console.log("Acceleration along X-axis: " + sensor.x);
    console.log("Acceleration along Y-axis: " + sensor.y);
    console.log("Acceleration along Z-axis: " + sensor.z);
}

sensor.onerror = event => console.log(event.error.name, event.error.message);
```

**Comment by Honry** [comment]
It's only implemented on Chrome, you can try the example on Chrome(at least Chrome 67), meanwhile the device you run on should have the accelerometer sensor.

Here's an [article ](https://developers.google.com/web/updates/2017/09/sensors-for-the-web)wrote by the API editors and implementors may guide you to get started on using Generic Sensor API.

**Comment by kenchris** [comment]
There is also a polyfill https://github.com/kenchris/sensor-polyfills you can use

**Comment by n1705771** [comment]
@Honry 
Thanks. I am sure I am using above Chrome 67. As my last comment, when I called in my angular project, I still have the error " Cannot find name 'Accelerometer' ".

**Comment by n1705771** [comment]
@kenchris Thanks!

**Comment by Honry** [comment]
Have you tried your code on Chrome? Does it work?

**Comment by n1705771** [comment]
@Honry yes. I tried it on Chrome.

**Comment by n1705771** [comment]
@kenchris Thanks! I installed the module and imported the Accelerometer class in the component. Then I call the Accelerometer(), it works.
