### ISSUE TITLE
Migrate all demos to at least Polymer 3.0

### ISSUE THREAD

**Issue by kenchris** [intel/generic-sensor-demos#64]
HTML imports and the like are being removed from Chrome in 2019 Q1 and these are not good demos using deprecated web tech.

I would also recommend moving to LitElement directly but using Polymer 3.0 components until the mwc-elements are ready.

**Comment by rakuco** [comment]
@Honry @kaixinjxq

**Comment by Honry** [comment]
I think @kaixinjxq would like to take this task. :)

**Comment by kaixinjxq** [comment]
Yeah, @rakuco, pls. assign it to me.

**Comment by rakuco** [comment]
Hmm, you're not part of the organization so I can't assign the issue to you, but please go ahead :)

**Comment by rakuco** [comment]
ping @kaixinjxq

**Comment by kaixinjxq** [comment]
@rakuco, all demos had been upgraded to Polymer 3.0, except the sensor-info(#80) is still under review, could you please take a look?

**Comment by rakuco** [comment]
I guess we can finally close this now that #80 was merged. Thanks everyone!
