### ISSUE TITLE
Not working on raspberry

### ISSUE THREAD

**Issue by albrasic** [intel/generic-sensor-demos#76]
I tried to run the demos from Raspberry. First, my Android phone takes almost forever before connecting to the server on Raspberry, second, the log console of the mobile browser says the web page cannot be found and finally, when the page of the demo is loaded on mobile Chrome, no sensor appears to be supported (not even the accelerometer, which I can access by simpler APIs than this demo). Thanks for any idea.

**Comment by rakuco** [comment]
Are you serving the pages over HTTPS? The sensor APIs are only available over secure connections.

**Comment by albrasic** [comment]
Yes! The command: polymer serve build/bundled --hostname 0.0.0.0 --protocol https/1.1 serves the application over https. It looks like the Chrome flag #allow-insecure-localhost yields a better view of the pages when it is enabled. Thanks again!

**Comment by albrasic** [comment]
One more point is that the port to be accessed is 8081 and not 8000, as suggested by the response to the command. And the browser flag about allowing insecure localhost does not really matter.

**Comment by albrasic** [comment]
Sorry again, it stopped working once more: the web page takes forever (same as before when it was served over http) and is shown right away only when the raspberry is turned off or when the demo is accessed remotely from my PC (which is USB-connected to the Android phone). The log console then complains about "Subject Alternative Name missing" and then reports "ERR_CERT_AUTHORITY_INVALID", while saying that "the connection is secure" and "the resources are served securely". Thanks in advance.

**Comment by rakuco** [comment]
@kenchris does this ring any bells based on how Polymer serves pages via https?

**Comment by albrasic** [comment]
I re-installed everything and it works now, although a bit slow. Before closing this thread, can you tell me whether the Security Certificates, key.pem and cert.pem, are generated simply by the command "polymer serve --protocol https/1.1" and whether they are referred to by any of the js files in the sensor-info folder (I'm trying to modify the demo in order to record and display sensor data over time)? Thanks again for your help.

**Comment by rakuco** [comment]
> can you tell me whether the Security Certificates, key.pem and cert.pem, are generated simply by the command "polymer serve --protocol https/1.1"

I don't think they are, as they're supposed to be actual certificates for your web server (I recently had to generate some self-signed ones via `openssl` to serve those files to another machine for testing too).

> and whether they are referred to by any of the js files in the sensor-info folder (I'm trying to modify the demo in order to record and display sensor data over time)?

They are not. The code doesn't assume anything about the environment it runs in as far as I can see (as they're supposed to work without `polymer-cli` too).

**Comment by rakuco** [comment]
Sorry it took so long to respond to this one! I guess we can close it now.
