### ISSUE TITLE
Ambient Map: The background style doesn't change

### ISSUE THREAD

**Issue by kaixinjxq** [intel/generic-sensor-demos#83]
Load the page first, when the illuminance less than 10, the map should uses night mode otherwise day mode. But after my PR(#81), the background doesn't change while the illuminance is changed. (It can be initially in night mode).
My google map api-key doesn't work, so I can't debug very well. The root cause may relate to following two changes against previous code.
Diff codes:
Before:
```
if (this.isNightMode)
  this.$.mapElement.map.set('styles', this.nightStyles);
else
  this.$.mapElement.map.set('styles', []);
```
After:
```
this.mapElement = this.shadowRoot.querySelector('#mapElement');
this.mapElement.set('styles', this.isNightMode ? this.nightStyles : []);
```

Before:
`styles` is a property.

After:
`styles` is a attribute.

@kenchris, do you have any idea?

**Comment by kenchris** [comment]
mapElement is a <google-map> element and it has an API. Looks like you need to call `.map.set` and not just `.set`

**Comment by kaixinjxq** [comment]
Thanks @kenchris.
I test the code in firstUpdated():
```
this.mapElement = this.shadowRoot.querySelector('#mapElement');
console.log(this.mapElement.map);  // null
console.log(this.shadowRoot.querySelector('#map'));  //null 
```
But I notice there is `if (!this.$.mapElement.map) return` in old code, so maybe google map create `map` element need a little time.
I will create a PR to add `.map`.
