### ISSUE TITLE
browsers support

### ISSUE THREAD

**Issue by Ajasra** [intel/generic-sensor-demos#93]
Looks like the latest Firefox, Chrome, and Safari doesn`t support generic sensors API?

**Comment by rakuco** [comment]
It's definitely supported on Chrome -- did you try any specific demo that didn't work?

**Comment by Chinedu25** [comment]
does it have something to running the projects with localserver, cuz it shows your browser doesnt support sensors?

**Comment by anssiko** [comment]
@Chinedu25 please see https://web.dev/generic-sensor/#development-environment to get started with development.

(I’ll close this issue to better focus discussion. Feel free to open a new issue with details on your browser, its version, OS and project(s) you’re experiementing with so we can help you better.)
